// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using theDeadlines.DAL.Models;

#nullable disable

namespace theDeadlines.DAL.Migrations
{
    [DbContext(typeof(DeadlinesContext))]
    [Migration("20250216143943_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("theDeadlines.DAL.Models.Checklist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<Guid>("SubDeadlineId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("sub_deadline_id");

                    b.HasKey("Id")
                        .HasName("PK__Checklis__3213E83F7436A59C");

                    b.HasIndex("SubDeadlineId");

                    b.ToTable("Checklist");
                });

            modelBuilder.Entity("theDeadlines.DAL.Models.ChecklistItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("ChecklistId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("checklist_id");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_completed");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__Checklis__3213E83F2AFA52A5");

                    b.HasIndex("ChecklistId");

                    b.ToTable("ChecklistItem");
                });

            modelBuilder.Entity("theDeadlines.DAL.Models.Deadline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__Deadline__3213E83F60841816");

                    b.ToTable("Deadline");
                });

            modelBuilder.Entity("theDeadlines.DAL.Models.SubDeadline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DeadlineDate")
                        .HasColumnType("datetime")
                        .HasColumnName("deadline_date");

                    b.Property<Guid>("DeadlineId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("deadline_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.HasKey("Id")
                        .HasName("PK__SubDeadl__3213E83F351D4B4C");

                    b.HasIndex("DeadlineId");

                    b.ToTable("SubDeadline");
                });

            modelBuilder.Entity("theDeadlines.DAL.Models.Checklist", b =>
                {
                    b.HasOne("theDeadlines.DAL.Models.SubDeadline", "SubDeadline")
                        .WithMany("Checklists")
                        .HasForeignKey("SubDeadlineId")
                        .IsRequired()
                        .HasConstraintName("FK__Checklist__sub_d__3C69FB99");

                    b.Navigation("SubDeadline");
                });

            modelBuilder.Entity("theDeadlines.DAL.Models.ChecklistItem", b =>
                {
                    b.HasOne("theDeadlines.DAL.Models.Checklist", "Checklist")
                        .WithMany("ChecklistItems")
                        .HasForeignKey("ChecklistId")
                        .IsRequired()
                        .HasConstraintName("FK__Checklist__check__403A8C7D");

                    b.Navigation("Checklist");
                });

            modelBuilder.Entity("theDeadlines.DAL.Models.SubDeadline", b =>
                {
                    b.HasOne("theDeadlines.DAL.Models.Deadline", "Deadline")
                        .WithMany("SubDeadlines")
                        .HasForeignKey("DeadlineId")
                        .IsRequired()
                        .HasConstraintName("FK__SubDeadli__deadl__398D8EEE");

                    b.Navigation("Deadline");
                });

            modelBuilder.Entity("theDeadlines.DAL.Models.Checklist", b =>
                {
                    b.Navigation("ChecklistItems");
                });

            modelBuilder.Entity("theDeadlines.DAL.Models.Deadline", b =>
                {
                    b.Navigation("SubDeadlines");
                });

            modelBuilder.Entity("theDeadlines.DAL.Models.SubDeadline", b =>
                {
                    b.Navigation("Checklists");
                });
#pragma warning restore 612, 618
        }
    }
}
