// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace theDeadlines.DAL.Models;

[Table("Checklist")]
public partial class Checklist
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("name")]
    [StringLength(50)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column("sub_deadline_id")]
    public int SubDeadlineId { get; set; }

    [InverseProperty("Checklist")]
    public virtual ICollection<ChecklistItem> ChecklistItems { get; set; } = new List<ChecklistItem>();

    [ForeignKey("SubDeadlineId")]
    [InverseProperty("Checklists")]
    public virtual SubDeadline SubDeadline { get; set; }
}