// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace theDeadlines.DAL.Models;

[Table("ChecklistItem")]
public partial class ChecklistItem
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("name")]
    [StringLength(100)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column("is_completed")]
    public bool IsCompleted { get; set; }

    [Column("checklist_id")]
    public int ChecklistId { get; set; }

    [ForeignKey("ChecklistId")]
    [InverseProperty("ChecklistItems")]
    public virtual Checklist Checklist { get; set; }
}