// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace theDeadlines.DAL.Models;

[Table("Deadline")]
public partial class Deadline
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("name")]
    [StringLength(100)]
    [Unicode(false)]
    public string Name { get; set; }

    [InverseProperty("Deadline")]
    public virtual ICollection<SubDeadline> SubDeadlines { get; set; } = new List<SubDeadline>();
}