// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using theDeadlines.Abstraction.IModels;

namespace theDeadlines.DAL.Models;

[Table("Deadline")]
public partial class Deadline : IDeadline
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; }

    [Column("name")]
    [StringLength(100)]
    [Unicode(false)]
    public string Name { get; set; }

    [InverseProperty("Deadline")]
    public virtual ICollection<SubDeadline> SubDeadlines { get; set; } = new List<SubDeadline>();

    ICollection<ISubDeadline> IDeadline.SubDeadlines
    {
        get => SubDeadlines.Cast<ISubDeadline>().ToList();
        set => SubDeadlines = value.Cast<SubDeadline>().ToList();
    }
}