// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using theDeadlines.Abstraction.IModels;

namespace theDeadlines.DAL.Models;

[Table("SubDeadline")]
public partial class SubDeadline : ISubDeadline
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; }

    [Column("description", TypeName = "text")]
    public string Description { get; set; }

    [Column("deadline_id")]
    public Guid DeadlineId { get; set; }

    [Column("deadline_date", TypeName = "datetime")]
    public DateTime? DeadlineDate { get; set; }

    [InverseProperty("SubDeadline")]
    public virtual ICollection<Checklist> Checklists { get; set; } = new List<Checklist>();

    ICollection<IChecklist> ISubDeadline.Checklists
    {
        get => Checklists.Cast<IChecklist>().ToList();
        set => Checklists = value.Cast<Checklist>().ToList();
    }

    [ForeignKey("DeadlineId")]
    [InverseProperty("SubDeadlines")]
    public virtual Deadline Deadline { get; set; }

    IDeadline ISubDeadline.Deadline
    {
        get => Deadline;
        set => Deadline = (Deadline)value;
    }
}