// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace theDeadlines.DAL.Models;

[Table("SubDeadline")]
public partial class SubDeadline
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("description", TypeName = "text")]
    public string Description { get; set; }

    [Column("deadline_id")]
    public int DeadlineId { get; set; }

    [Column("deadline_date", TypeName = "datetime")]
    public DateTime? DeadlineDate { get; set; }

    [InverseProperty("SubDeadline")]
    public virtual ICollection<Checklist> Checklists { get; set; } = new List<Checklist>();

    [ForeignKey("DeadlineId")]
    [InverseProperty("SubDeadlines")]
    public virtual Deadline Deadline { get; set; }
}